SET STATISTICS IO ON;
GO
SELECT * FROM [active_heap] WHERE [id] BETWEEN 501 AND 1000;
GO
SELECT * FROM [active_cluster] WHERE [id] BETWEEN 501 AND 1000;
GO

DBCC FREEPROCCACHE;
DBCC DROPCLEANBUFFERS;
GO
SELECT TOP(500) * FROM [active_heap];
GO
SELECT TOP(500) * FROM [active_cluster];
GO