use [master]
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
/*====  SQL Server 2025 version  ====*/
CREATE VIEW sys.dm_resource_governor_resource_pools AS
 	SELECT
 		pool_id,
 		name,
 		statistics_start_time,
 		total_cpu_usage_ms,
 		cache_memory_kb,
 		compile_memory_kb,
 		used_memgrant_kb,
 		total_memgrant_count,
 		total_memgrant_timeout_count,
 		active_memgrant_count,
 		active_memgrant_kb,
 		memgrant_waiter_count,
 		max_memory_kb,
 		used_memory_kb,
 		target_memory_kb,
 		out_of_memory_count,
 		min_cpu_percent,
 		max_cpu_percent,
 		isnull(cast(min_memory_percent as int), 0) min_memory_percent,
 		isnull(cast(max_memory_percent as int), 0) max_memory_percent,
 		cap_cpu_percent,
 		min_iops_per_volume,
 		max_iops_per_volume,
 		read_io_queued_total,
 		read_io_issued_total,
 		read_io_completed_total,
 		read_io_throttled_total,
 		read_bytes_total,
 		read_io_stall_total_ms,
 		read_io_stall_queued_ms,
 		write_io_queued_total,
 		write_io_issued_total,
 		write_io_completed_total,
 		write_io_throttled_total,
 		write_bytes_total,
 		write_io_stall_total_ms,
 		write_io_stall_queued_ms,
 		io_issue_violations_total,
 		io_issue_delay_total_ms,
 		io_issue_ahead_total_ms,
 		reserved_io_limited_by_volume_total,
 		io_issue_delay_non_throttled_total_ms,
 		total_cpu_delayed_ms,
 		total_cpu_active_ms,
 		total_cpu_violation_delay_ms,
 		total_cpu_violation_sec,
		total_cpu_usage_preemptive_ms,
		total_cpu_usage_actual_ms
	FROM OpenRowSet(TABLE DM_RG_POOLS, 1)


/*====  SQL Server 2022 version  ====*/
CREATE VIEW sys.dm_resource_governor_resource_pools AS
 	SELECT
 		pool_id,
 		name,
 		statistics_start_time,
 		total_cpu_usage_ms,
 		cache_memory_kb,
 		compile_memory_kb,
 		used_memgrant_kb,
 		total_memgrant_count,
 		total_memgrant_timeout_count,
 		active_memgrant_count,
 		active_memgrant_kb,
 		memgrant_waiter_count,
 		max_memory_kb,
 		used_memory_kb,
 		target_memory_kb,
 		out_of_memory_count,
 		min_cpu_percent,
 		max_cpu_percent,
 		isnull(cast(min_memory_percent as int), 0) min_memory_percent,
 		isnull(cast(max_memory_percent as int), 0) max_memory_percent,
 		cap_cpu_percent,
 		min_iops_per_volume,
 		max_iops_per_volume,
 		read_io_queued_total,
 		read_io_issued_total,
 		read_io_completed_total,
 		read_io_throttled_total,
 		read_bytes_total,
 		read_io_stall_total_ms,
 		read_io_stall_queued_ms,
 		write_io_queued_total,
 		write_io_issued_total,
 		write_io_completed_total,
 		write_io_throttled_total,
 		write_bytes_total,
 		write_io_stall_total_ms,
 		write_io_stall_queued_ms,
 		io_issue_violations_total,
 		io_issue_delay_total_ms,
 		io_issue_ahead_total_ms,
 		reserved_io_limited_by_volume_total,
 		io_issue_delay_non_throttled_total_ms,
 		total_cpu_delayed_ms,
 		total_cpu_active_ms,
 		total_cpu_violation_delay_ms,
 		total_cpu_violation_sec,
		total_cpu_usage_preemptive_ms
	FROM OpenRowSet(TABLE DM_RG_POOLS, 1)

