use [master]
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
CREATE VIEW sys.dm_external_governance_synchronizing_objects AS
	SELECT *
	FROM OpenRowset(TABLE DATABASE_EXTERNAL_GOVERNANCE_SYNCHRONIZING_OBJECTS)

